import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { CompiledOntology } from "../ontology/compiler.js";
import type { AnyOntology } from "../ontology/schemas/index.js";
import type {
  ArchitectureOntology,
  DomainOntology,
  CodeStyleOntology,
  AgentOntology,
  WorkflowOntology,
} from "../ontology/schemas/index.js";
import type { Rule } from "../ontology/schemas/base.schema.js";

const GENERATED_MARKER = "<!-- generated by ontoraness | do not edit manually -->";

/** docs/*.md 하나의 렌더링 결과 */
export interface RenderedDoc {
  id: string;
  filename: string;
  content: string;
}

/**
 * 컴파일된 온톨로지에서 섹션별 docs/*.md를 렌더링한다.
 * MetricsOntology는 docs 생성 대상이 아님.
 */
export function renderDocs(compiled: CompiledOntology): RenderedDoc[] {
  const docs: RenderedDoc[] = [];

  for (const onto of compiled.sources) {
    if (onto.kind === "MetricsOntology") continue;

    const doc = renderDoc(onto);
    if (doc) docs.push(doc);
  }

  return docs;
}

function renderDoc(onto: AnyOntology): RenderedDoc | null {
  const { id } = onto.metadata;

  switch (onto.kind) {
    case "ArchitectureOntology":
      return { id, filename: `${id}.md`, content: renderArchitecture(onto) };
    case "DomainOntology":
      return { id, filename: `${id}.md`, content: renderDomain(onto) };
    case "CodeStyleOntology":
      return { id, filename: `${id}.md`, content: renderCodeStyle(onto) };
    case "AgentOntology":
      return { id, filename: `${id}.md`, content: renderAgent(onto) };
    case "WorkflowOntology":
      return { id, filename: `${id}.md`, content: renderWorkflow(onto) };
    default:
      return null;
  }
}

/** 공통: rules[] 렌더링 */
function renderRules(rules: Rule[]): string {
  if (rules.length === 0) return "";

  const byTier = {
    tier1: rules.filter((r) => r.enforcement === "tier1"),
    tier2: rules.filter((r) => r.enforcement === "tier2"),
    tier3: rules.filter((r) => r.enforcement === "tier3"),
  };

  const lines: string[] = ["## 규칙"];

  for (const [tier, tierRules] of Object.entries(byTier)) {
    if (tierRules.length === 0) continue;
    const label =
      tier === "tier1" ? "핵심 (항상 적용)" :
      tier === "tier2" ? "가이드 (작업 시 참조)" :
      "강제 (코드 검사)";
    lines.push(`\n### ${label}`);

    for (const rule of tierRules) {
      const severityIcon =
        rule.severity === "error" ? "🔴" :
        rule.severity === "warning" ? "🟡" : "🔵";
      lines.push(`\n#### ${severityIcon} ${rule.name} \`${rule.id}\``);
      lines.push(rule.description);

      if (rule.examples?.valid?.length) {
        lines.push("\n**올바른 예시:**");
        rule.examples.valid.forEach((e) => lines.push(`- ${e}`));
      }
      if (rule.examples?.invalid?.length) {
        lines.push("\n**잘못된 예시:**");
        rule.examples.invalid.forEach((e) => lines.push(`- ❌ ${e}`));
      }
    }
  }

  return lines.join("\n");
}

function renderArchitecture(onto: ArchitectureOntology): string {
  const { name, description } = onto.metadata;
  const { spec } = onto;
  const lines = [
    GENERATED_MARKER,
    `# ${name}`,
    "",
    description,
    "",
  ];

  if (spec.layers?.length) {
    lines.push("## 레이어 구조");
    for (const layer of spec.layers) {
      lines.push(`\n### ${layer.name}`);
      lines.push(`- 경로 패턴: \`${layer.path_pattern}\``);
      if (layer.can_import_from.length) {
        lines.push(`- 참조 가능: ${layer.can_import_from.map((l) => `\`${l}\``).join(", ")}`);
      }
      if (layer.cannot_import_from?.length) {
        lines.push(`- 참조 금지: ${layer.cannot_import_from.map((l) => `\`${l}\``).join(", ")}`);
      }
    }
  }

  if (spec.patterns?.length) {
    lines.push("\n## 아키텍처 패턴");
    for (const p of spec.patterns) {
      lines.push(`\n### ${p.name}`);
      lines.push(p.description);
      lines.push(`> 규칙: ${p.rule}`);
    }
  }

  if (spec.constraints?.length) {
    lines.push("\n## 전역 제약");
    spec.constraints.forEach((c) => lines.push(`- ${c}`));
  }

  lines.push("", renderRules(spec.rules));
  return lines.join("\n");
}

function renderDomain(onto: DomainOntology): string {
  const { name, description } = onto.metadata;
  const { spec } = onto;
  const lines = [GENERATED_MARKER, `# ${name}`, "", description, ""];

  if (spec.bounded_contexts?.length) {
    lines.push("## Bounded Context");
    for (const ctx of spec.bounded_contexts) {
      lines.push(`\n### ${ctx.name}`);
      lines.push(`- 소유: ${ctx.owns.join(", ")}`);
      if (ctx.does_not_touch?.length) {
        lines.push(`- 접근 금지: ${ctx.does_not_touch.join(", ")}`);
      }
    }
  }

  if (spec.entities?.length) {
    lines.push("\n## 핵심 엔티티");
    for (const entity of spec.entities) {
      lines.push(`\n### ${entity.name}`);
      lines.push(entity.description);
      if (entity.attributes?.length) {
        lines.push("\n**속성:**");
        entity.attributes.forEach((a) =>
          lines.push(`- \`${a.name}\`: ${a.type}${a.description ? ` — ${a.description}` : ""}`)
        );
      }
      if (entity.invariants?.length) {
        lines.push("\n**불변 규칙:**");
        entity.invariants.forEach((inv) => lines.push(`- ${inv}`));
      }
    }
  }

  if (spec.glossary?.length) {
    lines.push("\n## 도메인 용어 (Ubiquitous Language)");
    for (const term of spec.glossary) {
      lines.push(`\n### ${term.term}`);
      lines.push(term.definition);
      if (term.code_representation) {
        lines.push(`\n\`\`\`\n${term.code_representation}\n\`\`\``);
      }
      if (term.enforcement) {
        lines.push(`> ${term.enforcement}`);
      }
    }
  }

  lines.push("", renderRules(spec.rules));
  return lines.join("\n");
}

function renderCodeStyle(onto: CodeStyleOntology): string {
  const { name, description } = onto.metadata;
  const { spec } = onto;
  const lines = [GENERATED_MARKER, `# ${name}`, "", description, ""];

  if (spec.naming) {
    lines.push("## 네이밍 컨벤션");
    const namingMap: Record<string, string> = {
      files: "파일명",
      classes: "클래스",
      functions: "함수",
      constants: "상수",
      types: "타입",
      interfaces: "인터페이스",
    };
    for (const [key, label] of Object.entries(namingMap)) {
      const val = spec.naming[key as keyof typeof spec.naming];
      if (val) lines.push(`- ${label}: \`${val}\``);
    }
  }

  if (spec.limits) {
    lines.push("\n## 크기 제한");
    const { file_lines_max, file_lines_recommended, function_lines_max, function_lines_recommended } = spec.limits;
    if (file_lines_max) lines.push(`- 파일 최대: ${file_lines_max}줄`);
    if (file_lines_recommended) lines.push(`- 파일 권장: ${file_lines_recommended}줄`);
    if (function_lines_max) lines.push(`- 함수 최대: ${function_lines_max}줄`);
    if (function_lines_recommended) lines.push(`- 함수 권장: ${function_lines_recommended}줄`);
  }

  if (spec.prohibitions?.length) {
    lines.push("\n## 금지 패턴");
    for (const p of spec.prohibitions) {
      const icon = p.severity === "error" ? "🔴" : "🟡";
      lines.push(`- ${icon} \`${p.pattern}\` — ${p.message}`);
    }
  }

  if (spec.requirements?.length) {
    lines.push("\n## 필수 요건");
    spec.requirements.forEach((r) => lines.push(`- ${r}`));
  }

  if (spec.preferred_libraries && Object.keys(spec.preferred_libraries).length > 0) {
    lines.push("\n## 권장 라이브러리");
    for (const [purpose, lib] of Object.entries(spec.preferred_libraries)) {
      lines.push(`- ${purpose}: \`${lib}\``);
    }
  }

  lines.push("", renderRules(spec.rules));
  return lines.join("\n");
}

function renderAgent(onto: AgentOntology): string {
  const { name, description } = onto.metadata;
  const { spec } = onto;
  const lines = [GENERATED_MARKER, `# ${name}`, "", description, ""];

  // Tier1 규칙 = 전역 제약 (never/always)
  const neverRules = spec.rules.filter(
    (r) => r.tags?.includes("never") || r.id.startsWith("never-")
  );
  const alwaysRules = spec.rules.filter(
    (r) => r.tags?.includes("always") || r.id.startsWith("always-")
  );

  if (neverRules.length || alwaysRules.length) {
    lines.push("## 전역 제약");
    if (neverRules.length) {
      lines.push("\n**절대 금지:**");
      neverRules.forEach((r) => lines.push(`- ❌ ${r.description}`));
    }
    if (alwaysRules.length) {
      lines.push("\n**항상 준수:**");
      alwaysRules.forEach((r) => lines.push(`- ✅ ${r.description}`));
    }
  }

  if (spec.roles?.length) {
    lines.push("\n## 에이전트 역할");
    for (const role of spec.roles) {
      lines.push(`\n### ${role.name}`);
      lines.push(role.description);
      if (role.responsibilities.length) {
        lines.push("\n**책임:**");
        role.responsibilities.forEach((r) => lines.push(`- ${r}`));
      }
      if (role.forbidden?.length) {
        lines.push("\n**금지:**");
        role.forbidden.forEach((f) => lines.push(`- ❌ ${f}`));
      }
    }
  }

  lines.push("", renderRules(spec.rules));
  return lines.join("\n");
}

function renderWorkflow(onto: WorkflowOntology): string {
  const { name, description } = onto.metadata;
  const { spec } = onto;
  const lines = [GENERATED_MARKER, `# ${name}`, "", description, ""];

  if (spec.workflows?.length) {
    lines.push("## 워크플로우");
    for (const wf of spec.workflows) {
      lines.push(`\n### ${wf.name}`);
      if (wf.trigger) lines.push(`> 트리거: ${wf.trigger}`);
      lines.push("\n**단계:**");
      wf.steps.forEach((step, i) => {
        const text = typeof step === "string" ? step : step.action;
        lines.push(`${i + 1}. ${text}`);
      });
    }
  }

  if (spec.checklists && Object.keys(spec.checklists).length > 0) {
    lines.push("\n## 체크리스트");
    for (const [name, items] of Object.entries(spec.checklists)) {
      lines.push(`\n### ${name}`);
      items.forEach((item) => lines.push(`- [ ] ${item}`));
    }
  }

  lines.push("", renderRules(spec.rules));
  return lines.join("\n");
}

/**
 * 렌더링된 docs를 지정 디렉토리에 파일로 쓴다.
 */
export async function writeDocs(
  docs: RenderedDoc[],
  docsDir: string
): Promise<void> {
  await mkdir(docsDir, { recursive: true });
  await Promise.all(
    docs.map((doc) =>
      writeFile(join(docsDir, doc.filename), doc.content, "utf-8")
    )
  );
}
