import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { CompiledOntology } from "../ontology/compiler.js";
import type { CodeStyleOntology } from "../ontology/schemas/index.js";

/** ESLint flat config 형태의 규칙 객체 */
export interface GeneratedEslintConfig {
  rules: Record<string, unknown>;
  /** 생성 근거 주석 (rule.id 기반) */
  sources: Record<string, string>;
}

/**
 * 컴파일된 온톨로지에서 Tier3 규칙을 추출해 ESLint flat config 파일을 생성한다.
 *
 * - CodeStyleOntology의 prohibitions → no-restricted-syntax 규칙
 * - limits.file_lines_max → max-lines 규칙
 * - naming 컨벤션 → @typescript-eslint/naming-convention 규칙
 */
export function generateEslintConfig(
  compiled: CompiledOntology
): GeneratedEslintConfig {
  const rules: Record<string, unknown> = {};
  const sources: Record<string, string> = {};

  const codeStyleOnto = compiled.sources.find(
    (o): o is CodeStyleOntology => o.kind === "CodeStyleOntology"
  );

  if (!codeStyleOnto) {
    return { rules, sources };
  }

  const { spec } = codeStyleOnto;

  // 1. 파일 크기 제한 → max-lines
  if (spec.limits?.file_lines_max) {
    rules["max-lines"] = ["warn", { max: spec.limits.file_lines_max }];
    sources["max-lines"] = `code-style: limits.file_lines_max=${spec.limits.file_lines_max}`;
  }

  // 2. 함수 크기 제한 → max-lines-per-function
  if (spec.limits?.function_lines_max) {
    rules["max-lines-per-function"] = [
      "warn",
      { max: spec.limits.function_lines_max },
    ];
    sources["max-lines-per-function"] =
      `code-style: limits.function_lines_max=${spec.limits.function_lines_max}`;
  }

  // 3. 금지 패턴 → no-restricted-syntax
  const prohibitions = spec.prohibitions ?? [];
  if (prohibitions.length > 0) {
    const restrictedSyntax = prohibitions
      .filter((p) => {
        // context 필드가 'production'인 경우만 포함 (기본값: 항상 적용)
        return !p.context || p.context === "production";
      })
      .map((p) => ({
        selector: patternToSelector(p.pattern),
        message: p.message,
      }))
      .filter((s) => s.selector !== null);

    if (restrictedSyntax.length > 0) {
      rules["no-restricted-syntax"] = [
        "error",
        ...restrictedSyntax,
      ];
      sources["no-restricted-syntax"] =
        `code-style: prohibitions (${prohibitions.length}개)`;
    }
  }

  // 4. Tier3 규칙에서 추가 ESLint 규칙 매핑
  const tier3Rules = compiled.tier3Rules.filter(
    (r) => r.tags?.includes("code-style") || r.tags?.includes("eslint")
  );

  for (const rule of tier3Rules) {
    const eslintRule = mapOntologyRuleToEslint(rule.id);
    if (eslintRule) {
      rules[eslintRule.name] = [
        rule.severity === "error" ? "error" : "warn",
        ...(eslintRule.options ?? []),
      ];
      sources[eslintRule.name] = `ontology: ${rule.id}`;
    }
  }

  return { rules, sources };
}

/**
 * ESLint flat config 파일 (.eslintrc.ontoraness.mjs)을 생성한다.
 */
export async function writeEslintConfig(
  config: GeneratedEslintConfig,
  outputPath: string = ".eslintrc.ontoraness.mjs"
): Promise<void> {
  if (Object.keys(config.rules).length === 0) return;

  const lines = [
    "// generated by ontoraness | do not edit manually",
    "// 온톨로지의 code-style.yml Tier3 규칙에서 자동 생성됨",
    "//",
    "// 사용법: eslint.config.mjs에서 import해서 rules에 병합하세요.",
    "// import ontoranessRules from './.eslintrc.ontoraness.mjs';",
    "",
    "export default {",
    "  rules: {",
  ];

  for (const [ruleName, ruleConfig] of Object.entries(config.rules)) {
    const source = config.sources[ruleName];
    if (source) {
      lines.push(`    // ${source}`);
    }
    lines.push(`    "${ruleName}": ${JSON.stringify(ruleConfig)},`);
  }

  lines.push("  },", "};", "");

  await writeFile(outputPath, lines.join("\n"), "utf-8");
}

// ── 유틸리티 ────────────────────────────────────────────────

/** 정규식 패턴 문자열을 ESLint selector로 변환 (단순 변환) */
function patternToSelector(pattern: string): string | null {
  // console.log → CallExpression
  if (pattern.includes("console.log")) {
    return "CallExpression[callee.object.name='console'][callee.property.name='log']";
  }
  if (pattern.includes("console")) {
    return "CallExpression[callee.object.name='console']";
  }
  if (pattern.includes("eval(")) {
    return "CallExpression[callee.name='eval']";
  }
  // 그 외 패턴은 지원하지 않음
  return null;
}

/** 온톨로지 rule.id → ESLint 규칙 매핑 */
function mapOntologyRuleToEslint(
  ruleId: string
): { name: string; options?: unknown[] } | null {
  const mappings: Record<string, { name: string; options?: unknown[] }> = {
    "no-console": { name: "no-console" },
    "no-eval": { name: "no-eval" },
    "no-debugger": { name: "no-debugger" },
    "eqeqeq": { name: "eqeqeq", options: ["always"] },
    "no-var": { name: "no-var" },
    "prefer-const": { name: "prefer-const" },
  };

  // ruleId에서 키워드 감지
  for (const [key, value] of Object.entries(mappings)) {
    if (ruleId.includes(key) || ruleId.includes(key.replace(/-/g, "_"))) {
      return value;
    }
  }

  return null;
}
