import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";

/** Claude Code settings.json에 주입할 훅 구조 */
interface ClaudeHook {
  type: "command";
  command: string;
}

interface ClaudeHookMatcher {
  matcher: string;
  hooks: ClaudeHook[];
}

interface ClaudeSettings {
  hooks?: {
    PreToolUse?: ClaudeHookMatcher[];
    PostToolUse?: ClaudeHookMatcher[];
    [key: string]: ClaudeHookMatcher[] | undefined;
  };
  [key: string]: unknown;
}

const HOOK_MARKER = "ontoraness";

/**
 * 훅 스크립트 파일을 생성한다.
 * 인라인 명령보다 스크립트 파일 방식이 훨씬 안정적이고 디버깅이 쉽다.
 * 배포 환경(node_modules/ontoraness)과 개발 환경(packages/core/dist) 모두 지원.
 */
async function writeHookScripts(rootDir: string): Promise<void> {
  const hooksDir = join(rootDir, ".claude/hooks");
  await mkdir(hooksDir, { recursive: true });

  const resolveCore = `
// ontoraness core 모듈 resolve:
// 1순위: node_modules/ontoraness (배포 환경)
// 2순위: packages/core/dist (개발 환경)
async function resolveCore() {
  try {
    return await import('ontoraness/dist/index.js');
  } catch {}
  try {
    return await import('@ontoraness/core');
  } catch {}
  const cwd = process.env.ONTORANESS_ROOT || process.cwd();
  const candidates = [
    cwd + '/packages/core/dist/index.js',
    cwd + '/node_modules/@ontoraness/core/dist/index.js',
  ];
  for (const p of candidates) {
    try { return await import(p); } catch {}
  }
  return null;
}
`.trim();

  const preScript = `#!/usr/bin/env node
// generated by ontoraness | PreToolUse hook — Tier3 규칙 위반 시 파일 작성 차단
${resolveCore}

const m = await resolveCore();
if (m) await m.checkViolation(process.env.TOOL_INPUT).catch(() => {});
`;

  const postScript = `#!/usr/bin/env node
// generated by ontoraness | PostToolUse hook — 경로 감지 → docs 주입 + 통계 기록
${resolveCore}

const m = await resolveCore();
if (m) await m.injectContext(process.env.TOOL_INPUT).catch(() => {});
`;

  await writeFile(join(hooksDir, "ontoraness-pre.mjs"), preScript, "utf-8");
  await writeFile(join(hooksDir, "ontoraness-post.mjs"), postScript, "utf-8");
}

/**
 * .claude/settings.json에 PreToolUse + PostToolUse 훅을 등록한다.
 * 이미 등록된 경우 덮어쓰지 않는다.
 */
export async function installHooks(rootDir: string = "."): Promise<void> {
  const settingsPath = join(rootDir, ".claude/settings.json");
  await mkdir(dirname(settingsPath), { recursive: true });

  // 훅 스크립트 파일 생성
  await writeHookScripts(rootDir);

  const preScript = resolve(rootDir, ".claude/hooks/ontoraness-pre.mjs");
  const postScript = resolve(rootDir, ".claude/hooks/ontoraness-post.mjs");

  // 기존 settings.json 읽기
  let settings: ClaudeSettings = {};
  if (existsSync(settingsPath)) {
    try {
      const raw = await readFile(settingsPath, "utf-8");
      settings = JSON.parse(raw) as ClaudeSettings;
    } catch {
      // 파싱 실패 시 빈 객체로 시작
    }
  }

  settings.hooks ??= {};

  // PreToolUse: Tier3 규칙 위반 시 파일 작성 차단
  settings.hooks.PreToolUse ??= [];
  const hasPreHook = settings.hooks.PreToolUse.some((h) =>
    h.hooks.some((hook) => hook.command.includes(HOOK_MARKER))
  );
  if (!hasPreHook) {
    settings.hooks.PreToolUse.push({
      matcher: "Write|Edit|MultiEdit",
      hooks: [{ type: "command", command: `node ${preScript}` }],
    });
  }

  // PostToolUse: 작업 경로 감지 → 관련 docs 주입 + 온톨로지 재컴파일
  settings.hooks.PostToolUse ??= [];
  const hasPostHook = settings.hooks.PostToolUse.some((h) =>
    h.hooks.some((hook) => hook.command.includes(HOOK_MARKER))
  );
  if (!hasPostHook) {
    settings.hooks.PostToolUse.push({
      matcher: "Write|Edit|MultiEdit",
      hooks: [{ type: "command", command: `node ${postScript}` }],
    });
  }

  await writeFile(settingsPath, JSON.stringify(settings, null, 2), "utf-8");
}

/**
 * 설치된 ontoraness 훅을 제거한다.
 */
export async function uninstallHooks(rootDir: string = "."): Promise<void> {
  const settingsPath = join(rootDir, ".claude/settings.json");
  if (!existsSync(settingsPath)) return;

  const raw = await readFile(settingsPath, "utf-8");
  const settings = JSON.parse(raw) as ClaudeSettings;

  if (!settings.hooks) return;

  const filterHooks = (matchers: ClaudeHookMatcher[]): ClaudeHookMatcher[] =>
    matchers
      .map((m) => ({
        ...m,
        hooks: m.hooks.filter((h) => !h.command.includes(HOOK_MARKER)),
      }))
      .filter((m) => m.hooks.length > 0);

  if (settings.hooks.PreToolUse) {
    settings.hooks.PreToolUse = filterHooks(settings.hooks.PreToolUse);
  }
  if (settings.hooks.PostToolUse) {
    settings.hooks.PostToolUse = filterHooks(settings.hooks.PostToolUse);
  }

  await writeFile(settingsPath, JSON.stringify(settings, null, 2), "utf-8");
}
