#!/usr/bin/env node
// generated by ontoraness | PostToolUse hook — 경로 감지 → docs 주입 + 통계 기록
// ontoraness core 모듈 resolve:
// 1순위: node_modules/ontoraness (배포 환경)
// 2순위: packages/core/dist (개발 환경)
async function resolveCore() {
  try {
    return await import('ontoraness/dist/index.js');
  } catch {}
  try {
    return await import('@ontoraness/core');
  } catch {}
  const cwd = process.env.ONTORANESS_ROOT || process.cwd();
  const candidates = [
    cwd + '/packages/core/dist/index.js',
    cwd + '/node_modules/@ontoraness/core/dist/index.js',
  ];
  for (const p of candidates) {
    try { return await import(p); } catch {}
  }
  return null;
}

const m = await resolveCore();
if (m) await m.injectContext(process.env.TOOL_INPUT).catch(() => {});
